### ISSUE TITLE
Pass raw LUH2 harvest data to FATES

### ISSUE THREAD

**Issue by glemieux** [glemieux/E3SM#30]
From https://github.com/ckoven/fates/issues/15#issuecomment-1783077290

**Comment by glemieux** [comment]
@ckoven should it be possible to use the luh2 state and transition data along with the luh2 raw harvest data at the same time?  Alternatively, should it be possible to only use the raw harvest data without the state + transitions data (and vice versa)?

Regarding logging vs. harvest, currently logging and harvest are separate namelist switches:
https://github.com/glemieux/E3SM/blob/0035cb362d2ddc650113c9f0e48d594d214f305a/components/elm/src/main/elmfates_interfaceMod.F90#L483-L500

That said, logging in fates is always turned on if harvest is set to `.true.`.  Do we want to keep this behavior for when using the raw luh2 harvest data or should that be separable as well?

**Comment by ckoven** [comment]
> ckoven should it be possible to use the luh2 state and transition data along with the luh2 raw harvest data at the same time

yes! harvest controls primary to secondary and secondary to secondary transition rates, transition matrix controls all other land use transitions.

**Comment by ckoven** [comment]
> Regarding logging vs. harvest, currently logging and harvest are separate namelist switches:
> https://github.com/glemieux/E3SM/blob/0035cb362d2ddc650113c9f0e48d594d214f305a/components/elm/src/main/elmfates_interfaceMod.F90#L483-L500
> 
> That said, logging in fates is always turned on if harvest is set to .true.. Do we want to keep this behavior for when using the raw luh2 harvest data or should that be separable as well?

yes, because harvest implies logging. though it actually seems possibly redundant since those two are essentially synonymous. possibly some simplification of the logic is in order.

**Comment by glemieux** [comment]
> > That said, logging in fates is always turned on if harvest is set to .true.. Do we want to keep this behavior for when using the raw luh2 harvest data or should that be separable as well?
> 
> yes, because harvest implies logging. though it actually seems possibly redundant since those two are essentially synonymous. possibly some simplification of the logic is in order.

@ckoven that was what I was wondering too.  Right now "harvest" means using external data to remove a certain amount of forest, where as "logging" means using a fates parameter driven methodology, right?   Logging appears to be fairly isolated to the fates-side of things; in fact we could refactor it to be turned on via a parameter file switch instead of a namelist variable, which we [note in a code comment](https://github.com/NGEET/fates/blob/a9bbfd820bb613afd0c33fe75404c7848b435260/biogeochem/EDLoggingMortalityMod.F90#L136-L138).  Note that having switches in the param file complicates testing, but Ryan's working on that general issue right now.

**Comment by glemieux** [comment]
Notes on `use_fates_logging` and `do_harvest` namelist options:

- `use_fates_logging` *only* tells the HLM to pass to fates the switch to turn on fates logging.
- `do_harvest` will *override* the `use_fates_logging` setting and to fates to set logging to `.true.` (this is silent to the user currently)
- `do_harvest` is tied up with the dynSubgrid file structure and as such needs `flanduse_timeseries` to be set, which is unnecessary for when running with `use_fates_luh` mode. 
- `do_harvest` is necessary to call `dynHarvest_init` and `dynHarvest_interp` procedures.

Other notes:
- `wood_harvest_units` are defined in the HLM and currently only used to pass to fates, so it could be a parameter instead of a hardcoded option.  That said, this is necessary to pass to the HLM for the `dynHarvest_init` call to define the harvest category names to read in when using `use_fates_luh` timeseries.
- `dynFatesLanduseInit` is called after *`dynSubgrid_init`* (and `dynHarvest_init` within) which means that passing the LUH2 timeseries data into the dynHarvest routines won't work as currently written.

Takeaways:
1. We can easily reuse/refactor the `use_fates_logging` (generalize to `fates_harvest_mode`?) since it only affects a tiny portion of code
2. The dynSubgrid `do_harvest` logic in the namelist perl code needs an update to take into account using fates LUH2 timeseries data
3. I think we may need to fold the LUH2 timeseries data fully into the dynSubgrid file structure.

**Comment by glemieux** [comment]
Reworking the `use_fates_logging` namelist option into a mode (`fates_harvest_mode`):
| Mode # | Mode description | `do_harvest` | `hlm_use_logging` | `use_fates_luh` |
| -- | -- | -- | -- | -- |
| 0 | No fates logging/harvest | `.false.` | `.false.` | either |
| 1 | Only fates logging | `.false.` | `.true.` | either |
| 2 | CLM landuse data driven harvest | `.true.` | `.true.` | either |
| 3 | LUH2 data driven harvest | `.true.` | `.true.` | `.true.` |

This would be used in conjunction with a new `wood_harvest_units` parameter file option switch (per site).

**Comment by glemieux** [comment]
Reworking the `use_fates_logging` namelist option into a mode switch (`fates_harvest_mode`):
| Mode # | Mode description | `do_harvest` | `hlm_use_logging` | `use_fates_luh` |
| -- | -- | -- | -- | -- |
| `0` | No fates logging/harvest | `.false.` | `.false.` | either |
| `1` | Only fates logging | `.false.` | `.true.` | either |
| `2` | CLM landuse data driven harvest | `.true.` | `.true.` | `.false.`? |
| `3` | LUH2 data driven harvest | `.true.` | `.true.` | `.true.` |

In the table above, the `do_harvest` would be set silently in the namelist build perl code (similar to how sp mode sets no comp and fbg).  The `hlm_use_logging` is the fates-side logical that would be set using `set_fates_ctrlparams` in the HLM interface code.  For option `3` the `use_fates_luh` would be set silently as well.

Note, this would be used in conjunction with a new `wood_harvest_units` parameter file option switch (per site), allowing the user to define either 'area' or 'mass' (integer) options.  This would be read-in and passed to the dynHarvestMod module.

@ckoven for option 2, would you want to be able to use the LUH state and transient data at the same time as the clm landuse data driven harvest?  My assumption is the answer is "no" because that would confuse things since the data isn't really aligned, correct?

**Comment by glemieux** [comment]
After discussion of the above, the updated plan is to more fully segregate the FATES LUH2 harvest data from dynHarvestMod as the ELM-FATES landuse code will eventually supersede dynHarvestMod.  Given this, do not convert the `wood_harvest_units` to a fates parameter file switch.

**Comment by glemieux** [comment]
- [x] update `dynFatesLandUseInit`
- [x] update `dynFatesLandUseInterp`
- [x] update `use_fates_logging` to `fates_harvest_mode`
- [x] make sure `get_do_harvest` isn't compatible with the `fates_harvest_mode > 3` (namelist build)
- [x] update fates API for `fates_harvest_mode` as necessary
- [x] revert commits updating dynHarvestMod
- [x] build test

**Comment by glemieux** [comment]
namelist option combination checks
- [x] `fates_harvest_mode=0` nominal check
- [x] `fates_harvest_mode=1` nominal check
- [ ] `fates_harvest_mode=2` check (skip for now, see below)
- [x] `fates_harvest_mode=3/4` nominal check
- [x] `fates_harvest_mode=3/4` + missing `fluh_timeseries` fail check
- [x] `fates_harvest_mode=3/4` + `use_fates_luh = .false.` fail check 
- [x] `fates_harvest_mode=3/4` + `do_harvest` fail check

Take care of `fates_harvest_mode=2` setup and check via https://github.com/glemieux/E3SM/issues/31.

**Comment by glemieux** [comment]
@ckoven FYI I merged `fates-luh2-harvest` into a new branch called `lnd/fates-landuse_v2-pft-harvest`, which I plan on using for the official e3sm PR to take over from `fates-landuse-pft`.

**Comment by glemieux** [comment]
- [ ] review and refactor fates-side to use namelist switch where harvest units previously used

**Comment by glemieux** [comment]
- [x] clarify the `do_harvest` incompatibility for `fates_harvest_mode > 2` options if only the `flanduse_timeseries` is set.

The code does fail gracefully, but the message is misleading somewhat.  It seems like `do_harvest` might automatically get set if `flanduse_timeseries` is not empty?

**Comment by glemieux** [comment]
> * [x]  clarify the `do_harvest` incompatibility for `fates_harvest_mode > 2` options if only the `flanduse_timeseries` is set.
> 
> The code does fail gracefully, but the message is misleading somewhat. It seems like `do_harvest` might automatically get set if `flanduse_timeseries` is not empty?

I confirmed that in the current build namelist setup, that `do_harvest` will not be automatically setup if `flanduse_timeseries` is set in the case build.  The model will build successfully.
