### ISSUE TITLE
Determine development needs to update elm-fates with spitfire mode options

### ISSUE THREAD

**Issue by glemieux** [glemieux/E3SM#6]
Ryan noted that we do not have the `Init2` routine and call in elmfates_interfaceMod.F90: https://github.com/ESCOMP/CTSM/blob/master/src/main/clm_initializeMod.F90#L457-L459

The elm code is setup to recognize the various spitfire mode options and pass them to fates, but we don't have any tests exercising this in e3sm or actual api code to appropriately initialize and read data for these modes.  

- [x] Get Charlie and Jennifer's feedback on prioritization
- [x] Double check ctsm test statuses
- [x] https://github.com/glemieux/E3SM/issues/8
- [x] Determine the development timeline for the spitfire updates

**Comment by glemieux** [comment]
@ckoven I realize I had created this issue for my task list this summer.  Do you have a prioritization for getting elm-fates to work with spitfire data modes?

**Comment by ckoven** [comment]
This will be needed/ highly desired for both pantropical (NGEE-Tropics) and global (E3SM) simulations, so I would say there is some amount of prioritization.

**Comment by glemieux** [comment]
For reference, this issue contains links to multiple issues and prs relevant to the fire data refactors that have taken place in clm: https://github.com/ESCOMP/CTSM/issues/982

**Comment by glemieux** [comment]
Discussion this with Charlie today, we bumped this in priority to be the next major project post-seed dispersal.  See [this planning spreadsheet](https://docs.google.com/spreadsheets/d/17FzcqZ_BpCu4kv9RfD9Voc4qfZRAWZi_BmKxNxY5UJw/edit#gid=0) for context.

**Comment by glemieux** [comment]
Closing as complete.
